name: instructlab
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - pytorch-cuda>=12,<13
  - cuda-toolkit>=12,<13
  - cuda-nvcc>=12,<13
  - pip
  - pip:
    - instructlab[cuda]==0.21.0
    - vllm>=0.6.2
variables:
  CMAKE_ARGS: "-DLLAMA_CUDA=on -DLLAMA_NATIVE=off"
  FORCE_CMAKE: 1
  CUDA_HOME: "${CONDA_PREFIX}"
  CUDA_USE_STATIC_CUDA_RUNTIME: "OFF"