name: instructlab
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - cudatoolkit=12.6
  - pip
  - pip:
    - instructlab[cuda]==0.21.0
    - vllm>=0.6.2
variables:
  CMAKE_ARGS: "-DLLAMA_CUDA=on -DLLAMA_NATIVE=off"
  FORCE_CMAKE: 1